name: Build

on:
  push

jobs:
  build:
    name: build test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install SwiftLint
        run: |
          brew install swiftlint

      - name: Run SwiftLint
        run: |
          export PATH="$PATH:/opt/homebrew/bin"
          if which swiftlint > /dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi

      - name: Archive Project
        run: |
          xcodebuild archive -project subtrack.xcodeproj \
                             -scheme subtrack \
                             -sdk iphoneos \
                             -configuration Release \
                             -archivePath MainApp.xcarchive \
                             CODE_SIGNING_ALLOWED=NO

