name: Build

on:
  push

jobs:
  build:
    name: build test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Archive Project
        run: |
          xcodebuild archive -project subtrack.xcodeproj \
                             -scheme subtrack \
                             -sdk iphoneos \
                             -configuration Release \
                             -archivePath MainApp.xcarchive \
                             CODE_SIGNING_ALLOWED=NO

